import ReduxProvider from "@/redux/reduxProvider";
import "./globals.css";

export const metadata = {
  title: "Coach finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}