
import ReduxProvider from "@/redux/ReduxProvider";
import "./globals.css";

export const metadata = {
  title: "coach finder group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
